### ISSUE TITLE
orc failed to initialize driver orc_brcm.so (Edge-Core Accton AS5610-52X)

### ISSUE THREAD

**Issue by ongrid** [opennetworklinux/ONL#157]
orc is unable to initialise on Edge-Core Accton AS5610-52X  48x10G + 4x40G  FreeScale P2020 Broadcom BCM56846 (Trident+), which claimed as "Supported and Tested" model.
Open Network Linux  a79666c (powerpc.all,2015.10.26.21.01,a79666ce1b4354264f62ae6bc09f93e20b4b3da7)

LOG:

```
root@onl-powerpc:~# orc
LOG:        load_driver.c:121 :: Found driver at: /usr/share/orc/drivers/orc_brcm.so
ERR:        load_driver.c:73  ::  Could not open Module /usr/share/orc/drivers/orc_brcm.so -- /usr/share/orc/drivers/orc_brcm.so: undefined symbol: aim_main
FATAL_ERR: /home/jenkins/workspace/ONL_Main/submodules/bigcode/modules/orc//module/src//main.c:257 ::Err: Failed to initialize driver at orc_brcm.so
exiting...

root@onl-powerpc:~# orc --debug=0 -V
LOG:            options.c:144 :: Setting Debug level to TRACE
DBG:        load_driver.c:118 :: Looking for driver at: /usr/share/orc/drivers/orc_brcm.so
LOG:        load_driver.c:121 :: Found driver at: /usr/share/orc/drivers/orc_brcm.so
ERR:        load_driver.c:73  ::  Could not open Module /usr/share/orc/drivers/orc_brcm.so -- /usr/share/orc/drivers/orc_brcm.so: undefined symbol: aim_main
FATAL_ERR: /home/jenkins/workspace/ONL_Main/submodules/bigcode/modules/orc//module/src//main.c:257 ::Err: Failed to initialize driver at orc_brcm.so
exiting...
```

orc_brcm.so is in place:

```
root@onl-powerpc:~# file /usr/share/orc/drivers/orc_brcm.so
/usr/share/orc/drivers/orc_brcm.so: ELF 32-bit MSB shared object, PowerPC or cisco 4500, version 1 (SYSV), dynamically linked, BuildID[sha1]=0xc9f3a71c8b1baeff02193bbc916b82acd0c584a6, with unknown capability 0x41000000 = 0x13676e75, with unknown capability 0x10000 = 0xb0401, stripped
```

**Comment by sonoble** [comment]
Hi, we should probably clarify what tested means, orc is a separate utility and we don't have orc support yet in some platforms including the 5610. We should have broadcom support.

**Comment by kvarlamo** [comment]
Ok, thanks. And how can we get Broadcom support on this?

**Comment by sonoble** [comment]
Hi, you can load the of-dpa drivers (they are in /lib/modules/3.9.6-OpenNetworkLinux-85xx/ofdpa) and use the of-dpa api, which is documented here: https://github.com/Broadcom-Switch/of-dpa/blob/master/doc/html/index.html . I will ask about orc support for the 5610.

**Comment by sonoble** [comment]
Hi, It appears we do have support for the 5610 but the patches were not pushed, we are currently building a image which will hopefully work and I will point you to it once it is done.

**Comment by kvarlamo** [comment]
Hi! Great news, we crossed fingers :-)

**Comment by olivermichel** [comment]
Hi,

were the patches for ORC pushed in the meantime? Also is it confirmed that of-dpa drivers will work with the 5610? We are currently experiencing the following error when connecting Ryu to of-dpa:

``indigo_ofdpa_driver: ERROR: Upsupported output port action (OFPP_CONTROLLER) 
for Table: 0 ``

Has anyone experienced this issue with the 5610?

Thank you, Oliver

**Comment by capveg** [comment]
Hi Oliver,

So while you didn't get a version of OF-DPA from us/ONL, I believe Accton
publishes one themselves - is that where you got it?  We're working on
OF-DPA support for all of the platforms that ONL supports but currently
it's only a subset.

That said, the error you're reporting is completely expected and not at all
a problem with OF-DPA.  The error says that Ryu is trying to push a
flow-mod into Table 0 with an unsupported action.  Programming for OF-DPA
(or real ASIC-based tables in general) is somewhat complicated because not
all tables accept all actions.  For a complete list of each table's
functionality and which matches and actions they support, please check out
the OF-DPA documentation here :
https://github.com/Broadcom-Switch/of-dpa/blob/master/OF-DPA-2.0/OFDPA_ASSV-ETP200-R.pdf
.

My guess is that RYU will have to have some of its subsystems updated to
work with OF-DPA.  If you're interested, here is some of the work that Ryan
Izard did to make Floodlight more compatible with OF-DPA:
https://github.com/floodlight/floodlight/pull/609

Also, if you would like to describe what you're trying to do, myself or
someone from the list would be happy to provide some pointers for which
flow mods to insert into which tables.

- Rob
.
