### ISSUE TITLE
ORC bcm_port numbers are random

### ISSUE THREAD

**Issue by nshopik** [opennetworklinux/ONL#91]
How bcm_port number related to orc# in linux? 

Currently bcm_port numbers are completely random. I've removed cable from ports 1,2 and it says 30 and 31 port link down, and then I pull cable from port 12 it says its bcm_port 5, SFP reported like 26,27,28,29. These numbers stay same after reboot.

This is make confusion and difficult to debugging 

This is only tested on quanta LB9, different hardware may have correct representation of numbers

**Comment by capveg** [comment]
So, you shouldn't have to worry about the broadcom port numbers -- they are meant for internal debugging.  Let me try to fix up the messages to clarify.

Just for your information, one of the annoying problems for programming these chips is that the front panel port (e.g., port number 1) which should correspond to Linux interface "orc01" does *not* map to the ASIC's internal port 1.  Because of the way the PCB's are laid out, some electrical engineer has figured out a crazy front panel port to ASIC port mapping that best preserves signal integrity in the trace and (ideally) reduces costs.  So there is no easy mapping formula from front panel ports to ASIC ports. 

Let me fix up the debugging messages to clarify.  Thx for the feedback.

But past that, everything is working?

**Comment by nshopik** [comment]
> Because of the way the PCB's are laid out, some electrical engineer has figured out a crazy front panel port to ASIC port mapping that best preserves signal integrity in the trace and (ideally) reduces costs.

Yeah I realize that a bit later, so it probably just need clear debug message to remove confusion. 

Today i've only tried to make LLDP work, but failed. It seems it tries forward them instead to punt into CPU.

**Comment by capveg** [comment]
Mind opening a different ticket for that?  I'm going to close this one out.

Thanks,

- Rob
.

**Comment by capveg** [comment]
This is fixed with orc-brcm 0.3.1 -- thanks for the feedback.


"{error:unknown type brcm_switch_port}LOG:        orcbrcm_drv.c:91  :: BRCM_DRV: Got link up event on port 6 (bcm_port 35)"
